#!/bin/bash
screeninstance=$(screen -ls | grep ungit);
if [ -n "${screeninstance}" ]; then
	zenity --info --text "UnGit già in esecuzione.";
	exit 0;
fi

ungitinstance=$(ps aux | grep ungit | grep node);
if [ -n "${ungitinstance}" ]; then
	zenity --info --text "UnGit già in esecuzione.";
	exit 0;
fi

screen -dmS ungit ungit
