#!/bin/bash
SRVHOST="sviluppo.cyb";
SRVUSER="root";
SRVPATH="/var/www/svnrepos";
SVNUSER="apache";
SVNGRUP="apache";
SVNCMD="svnadmin create";
SRVURL="http://sviluppo.cyb/svn-";

function Usage {
  echo "Uso: svncreate SVNPATH [LOCALPATH] [MESSAGE]";
  echo "or";
  echo "     svncreate SVNPATH [ZIPFILE] [MESSAGE]";
  exit 0;
}
if [ "$1" == "" ]; then
  Usage;
fi

SVNPATH=$1;
ssh ${SRVUSER}@${SRVHOST} "cd ${SRVPATH}; ${SVNCMD} ${SVNPATH}; chown -R ${SVNUSER}.${SVNGRUP} ${SVNPATH};";

SVNURL=${SRVURL}${SVNPATH};

if [ "$2" != "" ]; then
	LCLPATH=$2;
	if [ "$3" == "" ]; then
	  MESSAGE="Importazione iniziale";
	else
	  MESSAGE=$3;
	fi

	mkdir /tmp/svncreate;
	mkdir /tmp/svncreate/trunk;
	mkdir /tmp/svncreate/tags;
	mkdir /tmp/svncreate/branches;
	if [ "${LCLPATH:(-4)}" == ".zip" ]; then
		unzip ${LCLPATH} -d /tmp/svncreate/trunk/
	else
		cp -R ${LCLPATH}/* /tmp/svncreate/trunk/
	fi
	cd /tmp/svncreate

	svn import ${SVNURL} -m "${MESSAGE}";

	rm -fr /tmp/svncreate
fi

mkdir /tmp/svnconfig
cd /tmp/svnconfig
svn co ${SVNURL}/trunk trunk
cd trunk
svn propset svn:ignore "nbproject
.projectKnowledge
.classpath
.settings
.project
resources
temp
bin" .
svn commit -m "${MESSAGE} - Aggiunte directory ignorate"
cd
rm -fr /tmp/svnconfig

echo "SVN creato su ${SRVHOST}.";
echo "URL: ${SVNURL}";
