#!/bin/bash
if [ "$1" == "disable" ]; then
	echo "Unapplying network configuration";
	while read line; do
		d=$(echo $line | awk '{print $2}');
		if [ -n "$(mount | grep "$d")" ]; then
			echo "Unmounting $d";
			umount -f $d;
		fi
	done < <(cat /etc/dynmount/_current.fstab | grep -v '^#'| grep -v '^$');
	# hosts customization
	cat /etc/dynmount/base.hosts > /etc/hosts;
	echo "" > /etc/dynmount/_current.hosts;
	# fstab customization
	cat /etc/dynmount/base.fstab > /etc/fstab;
	echo "" > /etc/dynmount/_current.fstab;
fi

if [ "$1" == "enable" ]; then
	netcfg="";
	echo "netmount: detecting SSID";
	ssid="$(iwconfig 2>/dev/null| grep "ESSID" | grep -v 'off/any' | cut -d':' -f2 | sed -e's/[^0-9a-zA-Z_-]//g')";
	if [ -n "$ssid" ]; then
		echo "netmount: SSID detected: $ssid";
		for cf in /etc/dynmount/*.conf; do
			check="$(cat ${cf} | grep "SSID=${ssid}")";
			if [ -n "$check" ]; then
				netcfg=${cf};
			fi
		done
	fi
	if [ -n "${netcfg}" ]; then
		echo "netmount: SSID not found, detecting MAC address";
		mac="$(iwconfig 2>/dev/null | grep "Access Point" | grep -v 'Not-Associated' | awk '{print $6}')";
		echo "netmount: MAC detected: $mac";
		if [ -n "$mac" ]; then
			for cf in /etc/dynmount/*.conf; do
				check="$(cat ${cf} | grep "MAC=${mac}")";
				if [ -n "$check" ]; then
					netcfg=${cf};
				fi
			done
		fi
	fi
	if [ -n "${netcfg}" ]; then
		cfgname=$(basename ${netcfg});
		echo "Applying network configuration: ${cfgname}";
		# cleaning any previous customization
		$0 disable >/dev/null
		# hosts customization
		while read line; do
			echo ${line#*=} >> /etc/hosts;
			echo ${line#*=} >> /etc/dynmount/_current.hosts;
		done < <(cat ${netcfg} | grep '^HOSTS=');
		# fstab customization
		while read line; do
			mnt=${line#*=};
			mntpoint="$(echo "${mnt}" | awk '{print $2}')";
			echo "Preparing directory ${mntpoint}";
			mkdir -p ${mntpoint};
			chmod 777 ${mntpoint};
			echo ${mnt} >> /etc/fstab;
			echo ${mnt} >> /etc/dynmount/_current.fstab;
		done < <(cat ${netcfg} | grep '^FSTAB=');
	fi
fi
