#!/bin/bash
CONFIGFILE=$(distribute distconfig);
LOCALFILE=$1;
REMOTEFILE=$2;

if [ -f "$CONFIGFILE" ]; then
  for SERVER in $(distribute serverlist); do
    SSHPORT=$(distribute serverport $SERVER);
    SSHUSER=$(distribute serveruser $SERVER);
    scp ${SSHUSER}@${SERVER} -P ${LOCALFILE} ${REMOTEFILE}
  done
fi
