#!/bin/bash
CONFIGFILE=$(distribute distconfig);

if [ -f "$CONFIGFILE" ]; then
  for SERVER in $(distribute serverlist); do
    SSHPORT=$(distribute serverport $SERVER);
    SSHUSER=$(distribute serveruser $SERVER);
    SSHOUT=$(ssh ${SSHUSER}@${SERVER} -p${SSHPORT} "$1");
    echo "$SERVER : ${SSHOUT}";
  done
fi
