#!/bin/bash
CONFIGFILE=$(distribute distconfig);

if [ -f "$CONFIGFILE" ]; then
  for SERVER in $(distribute serverlist); do
    SSHPORT=$(distribute serverport $SERVER);
    SSHUSER=$(distribute serveruser $SERVER);
    echo "distribute exec: SERVER:$SERVER - COMMAND: $1";
    echo "----------------------------------------------------------------------------------";
    ssh ${SSHUSER}@${SERVER} -p${SSHPORT} "$1";
    echo
    echo
  done
fi
