#!/bin/bash
rightpad=108;
#rightpad=126;
function PrintTitolo {
  if [ "$2" == "" ]; then
    titlecolor="red";
  else
    titlecolor="$2";
  fi
  echo "<span weight=\"bold\" fgcolor=\"${titlecolor}\">$(/home/leandro/bin/rightalign "$1" $rightpad "=")</span>"
}
# System log
echo "<txt><span fgcolor=\"white\">$(/home/leandro/bin/rightalign "$(date +"%Y-%m-%d %H:%I:%S")" $rightpad)";
PrintTitolo "S y s t e m   l o g"
dmesg | tail -n 17 | sed -e's/</\&lt;/g' | sed -e's/>/\&gt;/g' | sed -e's/\[\([ 0-9\.]*\)\]/<span fgcolor="green">\[\1\]<\/span>/g'
# Process monitor
PrintTitolo "P r o c e s s   m o n i t o r";
ps aux | grep -v "%CPU" | awk '{print $3 " " $4 " " $11}' | sort -nr | head -n10
# System monitor
PrintTitolo "S y s t e m   m o n i t o r";
lanip=$(~/bin/collectip lan);
wanip=$(~/bin/collectip wan);
lantime=$(~/bin/collectip oldlan);
wantime=$(~/bin/collectip oldwan);
printf "<span weight=\"bold\" fgcolor=\"Red\">IP LAN: </span>%15s (Updated %5ds ago) <span weight=\"bold\" fgcolor=\"Red\">IP WAN: </span> %15s (Updated %5ds ago)\n" $lanip $lantime $wanip $wantime
# Disk usage
PrintTitolo "D i s k   U s a g e"
~/bin/diskmonitor sda3 Root
~/bin/diskmonitor sda4 Home
~/bin/diskmonitor sda2 Boot
# END
echo "</span></txt>"
