#!/bin/bash
BASEFILENAME="${HOME}/Capture.png";

if [ -n "$(which scrot 2>/dev/null)" ]; then
	scrot /tmp/grabscreen_out.png;
elif [ -n "$(which imlib2_grab 2>/dev/null)" ]; then
	imlib2_grab /tmp/grabscreen_out.png;
else
	echo "Cannot find a suitable screen shot program!";
	exit 1;
fi
if [ -n "$1" ]; then
	FILEOUT="$1";
else
	if [ -n "$(which zenity)" ]; then
		zenity --file-selection --filename=${BASEFILENAME} --save --confirm-overwrite >/tmp/grabscreen_name 2>&1
		FILEOUT="$(cat /tmp/grabscreen_name)";
	else
		Xdialog --fselect ${BASEFILENAME} 30 100 >/tmp/grabscreen_name 2>&1;
		FILENAME="$(cat /tmp/grabscreen_name)";
		if [ -n "$FILENAME" ]; then
			if [ -e "$FILENAME" ]; then
				RESP=$(Xdialog --yesno "$FILENAME\nfile already present, overwrite?" 8 40);
				if [ "$?" == "0" ]; then
					FILEOUT="$FILENAME";
				fi
			else
				FILEOUT="$FILENAME";
			fi
		fi
	fi
fi
if [ -n "$FILEOUT" ]; then
	mv /tmp/grabscreen_out.png $FILEOUT;
fi
