#!/bin/bash
if [ "$1" == "--onlykill" ]; then
	killall -9 conky
else 
	while [ "$(ps aux | grep xfdesktop | grep -v "grep")" == "" ]; do
		sleep 0.2;
	done;
	killall -9 conky
	rm -f ${HOME}/.conky/cache/*
	cd ${HOME}/.conky;
	if [ -e "${HOME}/.conky/top-left.rc" ]; then
		conky -c ${HOME}/.conky/top-left.rc
	fi
	if [ -e "$HOME/.conky/bottom-left.rc" ]; then
		conky -c ${HOME}/.conky/bottom-left.rc
	fi
	if [ -e "$HOME/.conky/top-right.rc" ]; then
		conky -c ${HOME}/.conky/top-right.rc
	fi
	if [ -e "$HOME/.conky/bottom-right.rc" ]; then
		conky -c ${HOME}/.conky/bottom-right.rc
	fi
fi
