#!/bin/bash
#touchpadname="SynPS/2 Synaptics TouchPad";
#touchpadname="ETPS/2 Elantech Touchpad";
#touchpadname="PS/2 Elantech ETF1059 Click-Pad";
if [ -z "$touchpadname" ]; then
	touchpadname=$(xinput list --name-only | grep -ie "touchpad" -ie "touch-pad" -ie "clickpad" -ie "click-pad");
fi
case "$1" in
  "enable")
    enabled="0";
    ;;
  "disable")
    enabled="1";
    ;;
  *)
    enabled=$(xinput list-props "$touchpadname" | grep "Device Enabled" | cut -d':' -f2 | awk '{print $1}');
    ;;
esac
if [ "$enabled" == "0" ]; then
	xinput enable "$touchpadname";
	echo "$touchpadname enabled";
else
	xinput disable "$touchpadname";
	echo "$touchpadname disabled";
fi
